version: 1.0.{build}
image: Visual Studio 2019
skip_tags: true
branches:
  only:
    - master
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: nBorIHYuu2rVs0/FKpffgywOvnxA3+E1fkstRpplRxRB261VPFiP+xX7GmR5tPqW
before_build:
  - dotnet restore
  - nuget install -Verbosity quiet opencover -Version 4.6.519 -OutputDirectory tools
  - nuget install -Verbosity quiet coveralls.net -Version 0.7.0 -OutputDirectory tools
build_script:
  - dotnet build -c Debug /p:DebugType=full
test_script:
  - ps: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute="NoCoverage"
  - ps: .\tools\coveralls.net.0.7.0\tools\csmacnz.coveralls.exe --opencover -i .\test\Piranha.Tests\coverage.opencover.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor
